language: c++

sudo: off

install: ./interpreter/meta/travis/install-ocaml.sh

script:
  - ./interpreter/meta/travis/build-test.sh
  - bash ./deploy.sh

os:
  - linux
  - osx

env:
  global:
    - ENCRYPTION_LABEL: "304454be9d6c"
    - COMMIT_AUTHOR_EMAIL: "littledan@igalia.com"
